<a href="https://colab.research.google.com/github/abdojulari/ExData_Plotting1/blob/master/stage_c_quiz.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [34]:
import pandas as pd 
import numpy as np
from sklearn.metrics import accuracy_score, recall_score, confusion_matrix, precision_score, f1_score
#from sklearn.preprocessing import LabelEncoder
from google.colab import files
uploaded = files.upload()

import io
dataset = pd.read_csv(io.BytesIO(uploaded['Data_for_UCI_named.csv']))
dataset.head()

Saving Data_for_UCI_named.csv to Data_for_UCI_named (2).csv


tau1      tau2      tau3  ...        g4      stab     stabf
0  2.959060  3.079885  8.381025  ...  0.958034  0.055347  unstable
1  9.304097  4.902524  3.047541  ...  0.781760 -0.005957    stable
2  8.971707  8.848428  3.046479  ...  0.109853  0.003471  unstable
3  0.716415  7.669600  4.486641  ...  0.362718  0.028871  unstable
4  3.134112  7.608772  4.943759  ...  0.820923  0.049860  unstable

[5 rows x 14 columns]

In [25]:
dataset['stab'].value_counts()

-0.007919    1
-0.023891    1
 0.000406    1
 0.075637    1
-0.014027    1
            ..
-0.046305    1
 0.013788    1
 0.043405    1
 0.051777    1
-0.001526    1
Name: stab, Length: 10000, dtype: int64

In [26]:
x = dataset.drop(columns=['stab', 'stabf'])
y = dataset['stabf']

In [27]:
#split the data into training and testing sets
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)


In [22]:
# feature scaling
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
x_train = sc_X.fit_transform(x_train)
x_test = sc_X.transform(x_test)

In [20]:
# fitting random forest classification to training set 

from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(random_state=1)
classifier.fit(x_train, y_train)

y_pred = classifier.predict(x_test)


In [21]:
# confusion Matrix 

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm


array([[ 625,   87],
       [  55, 1233]])

In [23]:
print(accuracy_score(y_test, y_pred))

0.929


In [28]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred, digits=4))

              precision    recall  f1-score   support

      stable     0.9191    0.8778    0.8980       712
    unstable     0.9341    0.9573    0.9456      1288

    accuracy                         0.9290      2000
   macro avg     0.9266    0.9176    0.9218      2000
weighted avg     0.9288    0.9290    0.9286      2000



In [30]:
recall = recall_score(y_test, y_pred, pos_label='stable')
print('Recall : {} '.format(round(recall*100), 2))

Recall : 88.0 


In [31]:
precision = precision_score(y_test, y_pred, pos_label='stable')
print('precision : {} '.format(round(precision*100), 2))

precision : 92.0 


In [35]:
f1 = f1_score(y_test, y_pred, pos_label='stable')
print('F1: {} '.format(round(f1*100), 2))

F1: 90.0 



**EXTRA TREES CLASSIFIER **

In [ ]:
from sklearn.ensemble import ExtraTreesClassifier
ETC = ExtraTreesClassifier(random_state =1)

In [36]:
from sklearn.ensemble import ExtraTreesClassifier
ETC = ExtraTreesClassifier(random_state =1)
ETC.fit(x_train, y_train)
ETC_pred = ETC.predict(x_test)

print(classification_report(y_test, ETC_pred, digits=4))

              precision    recall  f1-score   support

      stable     0.9410    0.8511    0.8938       712
    unstable     0.9218    0.9705    0.9455      1288

    accuracy                         0.9280      2000
   macro avg     0.9314    0.9108    0.9197      2000
weighted avg     0.9287    0.9280    0.9271      2000



In [39]:
ETC_conf_m =  confusion_matrix(y_test, ETC_pred)
ETC_conf_m



array([[ 606,  106],
       [  38, 1250]])

In [43]:
print('Accuracy Score for ExtraTreesClassifier: ',round((accuracy_score(y_test, ETC_pred) * 100),3))

Accuracy Score for ExtraTreesClassifier:  92.8


In [45]:
recall = recall_score(y_test, ETC_pred, pos_label='stable')
print('Recall for ExtraTreesClassifier : {} '.format(round(recall*100), 2))

Recall for ExtraTreesClassifier : 85.0 


In [46]:
precision = precision_score(y_test, ETC_pred, pos_label='stable')
print('precision for ExtraTreesClassifier : {} '.format(round(precision*100), 2))

precision for ExtraTreesClassifier : 94.0 


In [47]:
f1 = f1_score(y_test, ETC_pred, pos_label='stable')
print('F1 for ExtraTreesClassifier : {} '.format(round(f1*100), 2))

F1 for ExtraTreesClassifier : 89.0 


XGBOOST

In [49]:
from xgboost import XGBClassifier
XGB =  XGBClassifier(random_state=1)
XGB.fit(x_train, y_train)
XGB_pred =  XGB.predict(x_test)
print(classification_report(y_test, XGB_pred, digits=4))

              precision    recall  f1-score   support

      stable     0.9206    0.8469    0.8822       712
    unstable     0.9190    0.9596    0.9389      1288

    accuracy                         0.9195      2000
   macro avg     0.9198    0.9033    0.9105      2000
weighted avg     0.9195    0.9195    0.9187      2000



In [50]:
XGB_cm =  confusion_matrix(y_test, ETC_pred)
XGB_cm


array([[ 606,  106],
       [  38, 1250]])

In [51]:
print('Accuracy Score for XGB: ',round((accuracy_score(y_test, XGB_pred) * 100),3))

Accuracy Score for XGB:  91.95


In [52]:
recall = recall_score(y_test, XGB_pred, pos_label='stable')
print('Recall for XGB : {} '.format(round(recall*100), 2))

Recall for XGB : 85.0 


In [53]:
precision = precision_score(y_test, XGB_pred, pos_label='stable')
print('precision for XGB : {} '.format(round(precision*100), 2))

precision for XGB : 92.0 


In [54]:
f1 = f1_score(y_test, XGB_pred, pos_label='stable')
print('F1 for XGB : {} '.format(round(f1*100), 2))

F1 for XGB : 88.0 


LIGHTGBM 

In [55]:
from lightgbm import LGBMClassifier
LGBM =  LGBMClassifier(random_state=1)
LGBM.fit(x_train, y_train)
LGBM_pred =  LGBM.predict(x_test)
print(classification_report(y_test, LGBM_pred, digits=4))

              precision    recall  f1-score   support

      stable     0.9285    0.8933    0.9105       712
    unstable     0.9422    0.9620    0.9520      1288

    accuracy                         0.9375      2000
   macro avg     0.9353    0.9276    0.9313      2000
weighted avg     0.9373    0.9375    0.9372      2000



In [56]:
LGBM_cm =  confusion_matrix(y_test, LGBM_pred)
LGBM_cm


array([[ 636,   76],
       [  49, 1239]])

In [60]:
print('Accuracy Score for LGBM: ',round((accuracy_score(y_test, LGBM_pred) * 100),3))

Accuracy Score for LGBM:  94.0


In [61]:
recall = recall_score(y_test, LGBM_pred, pos_label='stable')
print('Recall for LGBM : {} '.format(round(recall*100), 2))

Recall for LGBM : 89.0 


In [62]:
precision = precision_score(y_test, LGBM_pred, pos_label='stable')
print('precision for LGBM : {} '.format(round(precision*100), 2))

precision for LGBM : 93.0 


In [63]:
f1 = f1_score(y_test, LGBM_pred, pos_label='stable')
print('F1 for LGBM : {} '.format(round(f1*100), 2))

F1 for LGBM : 91.0 
